---
- hosts: localhost
    connection: local
    gather_facts: no
    tasks:
        - name: Import VPC setup variables
          include_vars: vars/bastion_setup

        - name: Import VPC setup variables
          include_vars: vars/output_vars


